import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class SpecialVendingMachineGUI extends javax.swing.JFrame {
    private boolean specialVendingMachineCreated = false;

    /**
     * Creates new form SpecialVendingMachineGUI
     */
    public SpecialVendingMachineGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        specialVendingMachineLabel = new java.awt.Label();
        vendingMachineLabel = new java.awt.Label();
        BackToMainMenuButton = new javax.swing.JButton();
        createSpecialVendingMachineButton = new javax.swing.JButton();
        testSpecialVendingMachineButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        specialVendingMachineLabel.setAlignment(java.awt.Label.CENTER);
        specialVendingMachineLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        specialVendingMachineLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        specialVendingMachineLabel.setText("Special Vending Machine");

        vendingMachineLabel.setAlignment(java.awt.Label.CENTER);
        vendingMachineLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        vendingMachineLabel.setText("PIZZARIA VENDING MACHINE");

        BackToMainMenuButton.setText("Go Back to Main Menu");
        BackToMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMainMenuButtonActionPerformed(evt);
            }
        });

        createSpecialVendingMachineButton.setText("Create Special Vending Machine");
        createSpecialVendingMachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSpecialVendingMachineButtonActionPerformed(evt);
            }
        });

        testSpecialVendingMachineButton.setText("Test Special Vending Machine");
        testSpecialVendingMachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testSpecialVendingMachineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vendingMachineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createSpecialVendingMachineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BackToMainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(testSpecialVendingMachineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(specialVendingMachineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(vendingMachineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(specialVendingMachineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(createSpecialVendingMachineButton)
                                .addGap(15, 15, 15)
                                .addComponent(testSpecialVendingMachineButton)
                                .addGap(15, 15, 15)
                                .addComponent(BackToMainMenuButton)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * Event handler for the Back to Main Menu button click.
     * Hides the current frame and shows the VendingMachineGUI frame to return to the main menu.
     *
     * @param evt The ActionEvent triggered by clicking the button.
     */
    private void BackToMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new VendingMachineGUI().setVisible(true);
    }

    /**
     * Event handler for the Create Special Vending Machine button click.
     * Sets the specialVendingMachineCreated flag to true and displays a message dialog confirming the creation.
     *
     * @param evt The ActionEvent triggered by clicking the button.
     */
    private void createSpecialVendingMachineButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        specialVendingMachineCreated = true;
        JOptionPane.showMessageDialog(this, "Special Vending Machine created!");
    }

    /**
     * Event handler for the Test Special Vending Machine button click.
     * If the special vending machine is created, hides the current frame and shows the TestSpecialVendingMachine frame.
     * If the special vending machine is not created yet, displays a message dialog indicating that.
     *
     * @param evt The ActionEvent triggered by clicking the button.
     */
    private void testSpecialVendingMachineButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (specialVendingMachineCreated) {
            setVisible(false);
            new TestSpecialVendingMachine().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Special Vending Machine not created yet!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialVendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialVendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialVendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialVendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialVendingMachineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton BackToMainMenuButton;
    private javax.swing.JButton createSpecialVendingMachineButton;
    private java.awt.Label specialVendingMachineLabel;
    private javax.swing.JButton testSpecialVendingMachineButton;
    private java.awt.Label vendingMachineLabel;

    // End of variables declaration
}
