/**
 * A GUI class for testing regular vending machine features.
 * Extends javax.swing.JFrame.
 */
public class TestRegularVendingMachine extends javax.swing.JFrame {
    private VendingMachineController vendingMachineController;

    /**
     * Creates a new TestRegularVendingMachine instance.
     * Initializes the VendingMachineController and MaintenanceGUI.
     * Initializes the GUI components.
     */
    public TestRegularVendingMachine() {
        vendingMachineController = new VendingMachineController();

        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Initializes the GUI components for testing regular vending machine features.
     * Sets up buttons and their action listeners.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        BackToPreviousMenuButton1 = new javax.swing.JButton();
        testRegularVendingFeaturesButton = new javax.swing.JButton();
        testMaintenanceFeaturesButton = new javax.swing.JButton();
        testRegularVendingMachineLabel = new java.awt.Label();
        vendingMachineLabel1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackToPreviousMenuButton1.setText("Back to Previous Menu");
        BackToPreviousMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToPreviousMenuButton1ActionPerformed(evt);
            }
        });

        testRegularVendingFeaturesButton.setText("Test Regular Vending Features");
        testRegularVendingFeaturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testRegularVendingFeaturesButtonActionPerformed(evt);
            }
        });

        testMaintenanceFeaturesButton.setText("Test Maintenance Features");
        testMaintenanceFeaturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testMaintenanceFeaturesButtonActionPerformed(evt);
            }
        });

        testRegularVendingMachineLabel.setAlignment(java.awt.Label.CENTER);
        testRegularVendingMachineLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        testRegularVendingMachineLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        testRegularVendingMachineLabel.setText("Test Regular Vending Machine");

        vendingMachineLabel1.setAlignment(java.awt.Label.CENTER);
        vendingMachineLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        vendingMachineLabel1.setText("PIZZARIA VENDING MACHINE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vendingMachineLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(testRegularVendingFeaturesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BackToPreviousMenuButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(testMaintenanceFeaturesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(testRegularVendingMachineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(vendingMachineLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(testRegularVendingMachineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(testRegularVendingFeaturesButton)
                                .addGap(15, 15, 15)
                                .addComponent(testMaintenanceFeaturesButton)
                                .addGap(15, 15, 15)
                                .addComponent(BackToPreviousMenuButton1)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * Action performed when the "Back to Previous Menu" button is clicked.
     * Closes the current window and opens the regular vending machine menu.
     *
     * @param evt The ActionEvent triggered by clicking the "Back to Previous Menu" button.
     */
    private void BackToPreviousMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new RegularVendingMachineGUI().setVisible(true);
    }

    /**
     * Action performed when the "Test Regular Vending Features" button is clicked.
     * Closes the current window and opens the regular vending features testing window.
     *
     * @param evt The ActionEvent triggered by clicking the "Test Regular Vending Features" button.
     */
    private void testRegularVendingFeaturesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new RegularVendingGUI(vendingMachineController).setVisible(true);
    }

    /**
     * Action performed when the "Test Maintenance Features" button is clicked.
     * Closes the current window and opens the maintenance features testing window.
     *
     * @param evt The ActionEvent triggered by clicking the "Test Maintenance Features" button.
     */
    private void testMaintenanceFeaturesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new MaintenanceGUI(vendingMachineController).setVisible(true);
    }

    /**
     * Main method to start the application and display the test regular vending machine menu.
     * Sets the Nimbus look and feel and creates an instance of TestRegularVendingMachine.
     *
     * @param args The command line arguments (not used in this application).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestRegularVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestRegularVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestRegularVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestRegularVendingMachine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestRegularVendingMachine testRegularVendingMachine = new TestRegularVendingMachine();
                testRegularVendingMachine.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton BackToPreviousMenuButton1;
    private javax.swing.JButton testMaintenanceFeaturesButton;
    private javax.swing.JButton testRegularVendingFeaturesButton;
    private java.awt.Label testRegularVendingMachineLabel;
    private java.awt.Label vendingMachineLabel1;
    // End of variables declaration                   
}
