import javax.swing.*;

/**
 * The main GUI class for the Vending Machine application.
 * Extends javax.swing.JFrame.
 */
public class VendingMachineGUI extends javax.swing.JFrame {

    /**
     * Creates a new VendingMachineGUI instance and initializes the form.
     */
    public VendingMachineGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        regularVendingMachineButton = new javax.swing.JButton();
        specialVendingMachineButton = new javax.swing.JButton();
        mainMenuLabel = new java.awt.Label();
        vendingMachineLabel = new java.awt.Label();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Vending Machine Main Menu");
        setBackground(new java.awt.Color(255, 255, 255));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        regularVendingMachineButton.setText("Regular Vending Machine");
        regularVendingMachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularVendingMachineButtonActionPerformed(evt);
            }
        });

        specialVendingMachineButton.setText("Special Vending Machine");
        specialVendingMachineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialVendingMachineButtonActionPerformed(evt);
            }
        });

        mainMenuLabel.setAlignment(java.awt.Label.CENTER);
        mainMenuLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainMenuLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        mainMenuLabel.setText("Main Menu");

        vendingMachineLabel.setAlignment(java.awt.Label.CENTER);
        vendingMachineLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        vendingMachineLabel.setText("PIZZARIA VENDING MACHINE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vendingMachineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(regularVendingMachineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(specialVendingMachineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(vendingMachineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(regularVendingMachineButton)
                                .addGap(15, 15, 15)
                                .addComponent(specialVendingMachineButton)
                                .addGap(15, 15, 15)
                                .addComponent(exitButton)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * Action performed when the "Exit" button is clicked.
     * Displays an exit confirmation dialog and disposes the frame if the user confirms.
     *
     * @param evt The ActionEvent triggered by clicking the "Exit" button.
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String command = evt.getActionCommand();

        if("Exit".equals(command)){
            int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);

            if(option == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(this, "Thank you for using the vending machine. Please come again!");
                dispose();
            }
        }
    }

    /**
     * Action performed when the "Regular Vending Machine" button is clicked.
     * Sets the visibility of the current frame to false and opens a new RegularVendingMachineGUI frame.
     *
     * @param evt The ActionEvent triggered by clicking the "Regular Vending Machine" button.
     */
    private void regularVendingMachineButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new RegularVendingMachineGUI().setVisible(true);
    }

    /**
     * Action performed when the "Special Vending Machine" button is clicked.
     * Sets the visibility of the current frame to false and opens a new SpecialVendingMachineGUI frame.
     *
     * @param evt The ActionEvent triggered by clicking the "Special Vending Machine" button.
     */
    private void specialVendingMachineButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        setVisible(false);
        new SpecialVendingMachineGUI().setVisible(true);
    }

    /**
     * The main entry point for the VendingMachineGUI application.
     *
     * @param args The command line arguments.
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendingMachineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        int vmType;

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendingMachineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label mainMenuLabel;
    private javax.swing.JButton regularVendingMachineButton;
    private javax.swing.JButton specialVendingMachineButton;
    private java.awt.Label vendingMachineLabel;

    // End of variables declaration
}
